refactor(core): update slides
nolimits4web/swiper pull request #4241
Opened 2021-02-16 20:10 UTC by vltansky

2021-02-17 16:46 UTC, nolimits4web requested changes

2021-02-17 16:46 UTC, nolimits4web commented on src/components/core/update/updateSlides.js
> +    const swiper = this;
Let's move `const swiper = this` above the `const getDirectionLabel`, because right below we have same `const swiper = this` in upper scope

2021-02-17 16:46 UTC, nolimits4web commented on src/components/core/update/updateSlides.js
>    const swiper = this;
👆

2021-02-17 21:43 UTC, vltansky commented on src/components/core/update/updateSlides.js
>    const swiper = this;
?

2021-02-18 14:10 UTC, merged

2021-02-18 14:10 UTC, nolimits4web commented
All good, thanks!